[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "https://holzdesign-louis.ch/*"
  to = "https://www.holzdesign-louis.ch/:splat"
  status = 301
  force = true

[build.environment]
  NODE_VERSION = "18"
